### ISSUE TITLE
Android 5.1  登录注册成功后这个错误java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ligaoyang1111** [tencentyun/TUIRoomKit#170]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineJni.nativeInit(int, java.lang.String, java.lang.String, com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineJni$EngineConfig, com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineJni$ActionCallback) (tried Java_com_tencent_cloud_tuikit_engine_room_internal_TUIRoomEngineJni_nativeInit and Java_com_tencent_cloud_tuikit_engine_room_internal_TUIRoomEngineJni_nativeInit__ILjava_lang_String_2Ljava_lang_String_2Lcom_tencent_cloud_tuikit_engine_room_internal_TUIRoomEngineJni_00024EngineConfig_2Lcom_tencent_cloud_tuikit_engine_room_internal_TUIRoomEngineJni_00024ActionCallback_2)
        at com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineJni.nativeInit(Native Method)
        at com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineJni.init(TUIRoomEngineJni.java:45)
        at com.tencent.cloud.tuikit.engine.room.internal.TUIRoomEngineImpl.init(TUIRoomEngineImpl.java:36)
        at com.tencent.cloud.tuikit.engine.room.TUIRoomEngine.init(TUIRoomEngine.java:46)
        at com.tencent.cloud.tuikit.roomkit.model.manager.RoomEngineManager.setup(RoomEngineManager.java:62)
        at com.tencent.cloud.tuikit.roomkit.model.TUIRoomKitImpl.setup(TUIRoomKitImpl.java:45)
        at com.tencent.liteav.demo.MainActivity.init(MainActivity.java:38)
        at com.tencent.liteav.demo.MainActivity.onCreate(MainActivity.java:30)

**Comment by ligaoyang1111** [comment]
您好，这个错误要怎么解决？

**Comment by PualGeorge** [comment]
请检查您的工程根目录是否已经配置如下内容，您可以参考我们的接入文档https://cloud.tencent.com/document/product/647/81961。将我们的组件接入您的工程
![截屏2022-12-30 16 31 15](https://user-images.githubusercontent.com/59617863/210050444-038fe47e-9f81-4b4c-afb0-08ba3ddbb625.png)
