### ISSUE TITLE
web版 打包报错

### ISSUE THREAD

**Issue by LinYing89** [tencentyun/TUIRoomKit#75]
使用npm run build命令打包报错
D:\Documents\GitHub\trtctest\node_modules\vscode-jsonrpc\lib\common\linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Documents\GitHub\trtctest\node_modules\vscode-jsonrpc\lib\common\api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuiroom@0.0.0 build: `vue-tsc --noEmit --skipLibCheck && vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tuiroom@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-06-23T07_00_01_030Z-debug.log

**Comment by lixin0** [comment]
你好，辛苦检查一下 node 环境版本，建议升级到 v16 以上
